In [1]:
import pandas as pd

In [6]:
#pd.read_csv("C:/Users/smeai/Downloads/iqr.csv")

In [7]:
df=pd.read_csv("iqr.csv")

In [8]:
df.head()

    name  height
0  mohan     1.2
1  maria     2.3
2  sakib     4.9
3    tao     5.1
4  virat     5.2

In [9]:
df.head(10)

     name  height
0   mohan     1.2
1   maria     2.3
2   sakib     4.9
3     tao     5.1
4   virat     5.2
5  khusbu     5.4
6  dmitry     5.5
7  selena     5.5
8    john     5.6
9   imran     5.6

In [11]:
df.describe()

          height
count  20.000000
mean    8.390000
std     8.782812
min     1.200000
25%     5.350000
50%     5.700000
75%     6.275000
max    40.200000

In [13]:
df.info(0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    20 non-null     object
 1   height  20 non-null     float64
dtypes: float64(1), object(1)
memory usage: 312.0+ bytes

In [30]:
Q1=float(df.height.quantile(0.25))

# we have used the Quantile Function to get the exact Quantile Value

In [31]:
Q1

5.3500000000000005

In [32]:
Q3=float(df.height.quantile(0.75))

In [33]:
Q3

6.275

In [34]:
IQR=Q3-Q1

In [35]:
IQR

0.9249999999999998

In [36]:
lower_limit=Q1-1.5*IQR

In [37]:
upper_limit=Q3+1.5*IQR

In [38]:
lower_limit,upper_limit

(3.962500000000001, 7.6625)

In [41]:
df[(df.height<lower_limit)|(df.height>upper_limit)]
# These are all the Outliers Present in the Data

     name  height
0   mohan     1.2
1   maria     2.3
17  aamir    14.5
18    ken    23.2
19    Liu    40.2

In [42]:
df[(df.height>lower_limit)&(df.height<upper_limit)]

       name  height
2     sakib     4.9
3       tao     5.1
4     virat     5.2
5    khusbu     5.4
6    dmitry     5.5
7    selena     5.5
8      john     5.6
9     imran     5.6
10     jose     5.8
11  deepika     5.9
12   yoseph     6.0
13    binod     6.1
14  gulshan     6.2
15  johnson     6.5
16   donald     7.1